# Generated by Django 4.2.7 on 2023-12-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("directs", "0003_auto_20220213_2344"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="reciepient",
            new_name="recipient",
        ),
        migrations.AlterField(
            model_name="message",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
