# Generated by Django 4.2.7 on 2023-12-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0002_auto_20220211_2140"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
