# Generated by Django 5.0a1 on 2023-10-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0007_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default.jpg", null=True, upload_to="profile_picture"
            ),
        ),
    ]
