# Generated by Django 5.0a1 on 2023-10-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0009_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="d_o_b",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="nation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default.jpg", null=True, upload_to="profile_picture"
            ),
        ),
    ]
