# Generated by Django 5.0b1 on 2023-10-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0010_profile_d_o_b_profile_email_profile_nation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="d_o_e",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="doc_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
