# Generated by Django 5.0b1 on 2023-11-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0012_rename_doc_name_profile_doc_id_profile_id_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id_document",
            field=models.ImageField(null=True, upload_to="id_document"),
        ),
    ]
