# Generated by Django 5.0b1 on 2023-11-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0013_alter_profile_id_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id_document",
            field=models.ImageField(null=True, upload_to="id_documents"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default.jpg", null=True, upload_to="profile_pictures"
            ),
        ),
    ]
