# Generated by Django 5.0b1 on 2023-11-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0014_alter_profile_id_document_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id_document",
            field=models.ImageField(blank=True, null=True, upload_to="id_documents"),
        ),
    ]
