# Generated by Django 5.0b1 on 2023-11-06 02:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0016_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
    ]
