# Generated by Django 5.0b1 on 2023-11-10 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0019_alter_profile_id_document_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
