# Generated by Django 5.0b1 on 2023-11-18 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0021_alter_profile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="nation",
            new_name="country",
        ),
    ]
