# Generated by Django 4.2.7 on 2023-11-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authy", "0022_rename_nation_profile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(null=True, upload_to="profile_pictures"),
        ),
    ]
