# Generated by Django 4.2.7 on 2023-11-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0026_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='id_documents'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pictures'),
        ),
    ]
