# Generated by Django 4.2.7 on 2023-12-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0027_alter_profile_d_o_b_alter_profile_d_o_e'),
        ('authy', '0027_alter_profile_id_document_alter_profile_image'),
    ]

    operations = [
    ]
