# Generated by Django 4.2.7 on 2023-12-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0003_auto_20220214_1319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
